// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const clearchirps = `-- name: Clearchirps :exec
DELETE FROM chirps
`

func (q *Queries) Clearchirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearchirps)
	return err
}

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (gen_random_uuid(), Now(), Now(), $1, $2)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpParams struct {
	Body   string `json:"body"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
